### ISSUE TITLE
MissingMethodException

### ISSUE THREAD

**Issue by ugurcicekfidan** [Microsoft/GetVSTSBuildUsage#2]
Hi,

**GetBuildsAsync** method call throws **MissingMethodException**. What can i do to solve that problem? Using nuget package: _Microsoft.TeamFoundationServer.ExtendedClient.14.102.0_
Thanks.

Source Code:
`internal static List<Microsoft.TeamFoundation.Build.WebApi.Build> GetBuildDefinitions()
        {
            Uri uri = new Uri("<on-premise tfs uri>");
            var buildClient = new BuildHttpClient(uri, new VssAadCredential());
            VssConnection connection = new VssConnection(uri, new VssAadCredential());
            var projectClient = connection.GetClient<ProjectHttpClient>();
            var projects = projectClient.GetProjects().Result;
            buildClient = connection.GetClient<BuildHttpClient>();
            var definitions = buildClient.GetBuildsAsync(project: "TfxTarget");
            return definitions.Result;
        }`

> System.MissingMethodException was unhandled
>   HResult=-2146233069
>   Message=Method not found: 'System.Threading.Tasks.Task`1<!!0> Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.SendAsync(System.Net.Http.HttpMethod, System.Guid, System.Object, Microsoft.VisualStudio.Services.WebApi.ApiResourceVersion, System.Net.Http.HttpContent, System.Collections.Generic.IEnumerable`1<System.Collections.Generic.KeyValuePair`2<System.String,System.String>>, System.Object, System.Threading.CancellationToken)'.
>   Source=Microsoft.TeamFoundation.Build2.WebApi
>   StackTrace:
>        at Microsoft.TeamFoundation.Build.WebApi.BuildHttpClientBase.GetBuildsAsync(String project, IEnumerable`1 definitions, IEnumerable`1 queues, String buildNumber, Nullable`1 minFinishTime, Nullable`1 maxFinishTime, String requestedFor, Nullable`1 reasonFilter, Nullable`1 statusFilter, Nullable`1 resultFilter, IEnumerable`1 tagFilters, IEnumerable`1 properties, Nullable`1 type, Nullable`1 top, String continuationToken, Nullable`1 maxBuildsPerDefinition, Nullable`1 deletedFilter, Nullable`1 queryOrder, String branchName, Object userState, CancellationToken cancellationToken)
>        at ConsoleApplication5.Program.GetBuildDefinitions() in c:\Users\uc005129\Documents\Visual Studio 2013\Projects\ConsoleApplication5\ConsoleApplication5\Program.cs:line 28
>        at ConsoleApplication5.Program.Main(String[] args) in c:\Users\uc005129\Documents\Visual Studio 2013\Projects\ConsoleApplication5\ConsoleApplication5\Program.cs:line 13
>        at System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
>        at System.AppDomain.ExecuteAssembly(String assemblyFile, Evidence assemblySecurity, String[] args)
>        at Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly()
>        at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
>        at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
>        at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
>        at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
>        at System.Threading.ThreadHelper.ThreadStart()
>   InnerException: 

packages.config:
`<?xml version="1.0" encoding="utf-8"?>
<packages>
  <package id="Microsoft.AspNet.WebApi.Client" version="5.2.3" targetFramework="net451" />
  <package id="Microsoft.AspNet.WebApi.Core" version="5.2.3" targetFramework="net451" />
  <package id="Microsoft.IdentityModel.Clients.ActiveDirectory" version="3.13.5" targetFramework="net451" />
  <package id="Microsoft.TeamFoundationServer.Client" version="14.102.0" targetFramework="net451" />
  <package id="Microsoft.TeamFoundationServer.ExtendedClient" version="14.102.0" targetFramework="net451" />
  <package id="Microsoft.VisualStudio.Services.Client" version="14.102.0" targetFramework="net451" />
  <package id="Microsoft.VisualStudio.Services.InteractiveClient" version="14.102.0" targetFramework="net451" />
  <package id="Newtonsoft.Json" version="6.0.8" targetFramework="net451" />
  <package id="System.IdentityModel.Tokens.Jwt" version="4.0.0" targetFramework="net451" />
  <package id="WindowsAzure.ServiceBus" version="3.4.0" targetFramework="net451" />
</packages>`

**Comment by ugurcicekfidan** [comment]
formatting.
